spring.config.import=vault://
spring.cloud.vault.uri=${VAULT_URI}
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=${VAULT_TOKEN}
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.application-name=wms
spring.cloud.vault.kv.profile-separator=/
#CẤU HÌNH PostgreSQL cho production
spring.datasource.url=
spring.datasource.username=postgre
spring.datasource.password=0188
#CẤU HÌNH Flyway cho production ------------------
spring.flyway.clean-disabled=true
spring.flyway.out-of-order=false
