spring.config.import=vault://

spring.cloud.vault.uri=${VAULT_URI}
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=${VAULT_TOKEN}

spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.application-name=wms
spring.cloud.vault.kv.profile-separator=/
