spring.application.name=wms

spring.datasource.url=jdbc:postgresql://localhost:5432/wms
spring.datasource.username=postgres
spring.datasource.password=0188
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-only
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Google GenAI Placeholder Properties
spring.ai.google.genai.project-id=demo-project
spring.ai.google.genai.api-key=demo-key
spring.ai.vectorstore.google.project-id=demo-project

#Docker stop
spring.docker.compose.enabled=false