spring.application.name=wms

spring.datasource.url=jdbc:postgresql://localhost:5432/wms
spring.datasource.username=postgres
spring.datasource.password=0188
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Google GenAI Placeholder Properties
spring.ai.google.genai.project-id=demo-project
spring.ai.google.genai.api-key=demo-key
spring.ai.vectorstore.google.project-id=demo-project

#Docker stop
spring.docker.compose.enabled=false

# JWT Configuration
jwt.secret=your-super-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000

# Cấu hình Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# --- LETTUCE CONNECTION POOL CONFIGURATION ---
# Số lượng kết nối tối đa có thể hoạt động (mượn từ pool) tại một thời điểm
spring.data.redis.lettuce.pool.max-active=50

# Số lượng kết nối tối thiểu luôn được giữ ở trạng thái rảnh để phục vụ ngay lập tức
spring.data.redis.lettuce.pool.min-idle=10

# Số lượng kết nối tối đa được phép ở trạng thái rảnh trong pool
spring.data.redis.lettuce.pool.max-idle=20

# Thời gian tối đa (ms) mà một thread phải chờ để lấy được kết nối trước khi báo lỗi
spring.data.redis.lettuce.pool.max-wait=3000ms

# Thời gian chờ (ms) để thiết lập kết nối socket mới
spring.data.redis.lettuce.shutdown-timeout=100ms


# -----------------------------
# HIGH-CONCURRENCY (ENTERPRISE)
# -----------------------------
# Kích hoạt dũng sĩ Java 21 Virtual Threads (Loom) thay cho Standard Tomcat Threads (Mặc định 200)
spring.threads.virtual.enabled=true

# Giới hạn số lượng kết nối tới DB để bảo vệ PostgreSQL không bị "nhấn chìm" bởi Virtual Threads
# Dù Virtual Thread gánh 10,000 requests, DB cũng chỉ cấp tối đa 50 room kết nối đồng thời.
#số lượng kết nối tối đa
spring.datasource.hikari.maximum-pool-size=50
#số lượng kết nối tối thiểu
spring.datasource.hikari.minimum-idle=10


# -----------------------------
# KAFKA (EVENT-DRIVEN ARCHITECTURE)
# -----------------------------
# Trỏ mũi tiêm về con Docker Kafka ở cổng 9092
spring.kafka.bootstrap-servers=localhost:9092,localhost:9093,localhost:9094
# Tên của nhóm công nhân bốc vác (Consumer Group)
spring.kafka.consumer.group-id=wms-inventory-group
# Nếu đọc rớt mạng, đọc lại từ Message cũ nhất
spring.kafka.consumer.auto-offset-reset=earliest

# Cách giải mã Key và Value (thông thường là String)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

