--
-- PostgreSQL database dump
--

\restrict XFQ6PN2qt7h0h3dVcqeuLuk4mcwvYidjQfIPgR10eSZU9aH4OGcbmHww6istebx

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

-- Started on 2026-05-01 20:55:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 241 (class 1259 OID 303480)
-- Name: aut_permission_perwarehouse; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.aut_permission_perwarehouse (
                                                    id bigint NOT NULL,
                                                    created_at timestamp(6) without time zone,
                                                    updated_at timestamp(6) without time zone,
                                                    granted_at timestamp(6) without time zone NOT NULL,
                                                    grant_by bigint,
                                                    permission_id bigint NOT NULL,
                                                    user_id bigint NOT NULL,
                                                    warehouse_id bigint NOT NULL
);


ALTER TABLE public.aut_permission_perwarehouse OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 303479)
-- Name: aut_permission_perwarehouse_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.aut_permission_perwarehouse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aut_permission_perwarehouse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 303491)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
                                        id bigint NOT NULL,
                                        created_at timestamp(6) without time zone,
                                        updated_at timestamp(6) without time zone,
                                        code character varying(255) NOT NULL,
                                        description character varying(255)
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 303490)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 303695)
-- Name: auth_refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_refresh_token (
                                           id bigint NOT NULL,
                                           created_at timestamp(6) without time zone,
                                           updated_at timestamp(6) without time zone,
                                           created_by_ip character varying(64),
                                           expires_at timestamp(6) without time zone NOT NULL,
                                           replaced_by_token_hash character varying(255),
                                           revoked boolean NOT NULL,
                                           token_hash character varying(255) NOT NULL,
                                           user_agent character varying(512),
                                           user_id bigint NOT NULL
);


ALTER TABLE public.auth_refresh_token OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 303694)
-- Name: auth_refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 246118)
-- Name: auth_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_role (
                                  id bigint NOT NULL,
                                  created_at timestamp(6) without time zone,
                                  updated_at timestamp(6) without time zone,
                                  name character varying(255)
);


ALTER TABLE public.auth_role OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 246117)
-- Name: auth_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 246125)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
                                  id bigint NOT NULL,
                                  created_at timestamp(6) without time zone,
                                  updated_at timestamp(6) without time zone,
                                  email character varying(255),
                                  password character varying(255),
                                  username character varying(255)
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 246124)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 246133)
-- Name: auth_user_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_role (
                                       user_id bigint NOT NULL,
                                       role_id bigint NOT NULL
);


ALTER TABLE public.auth_user_role OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 303501)
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
                                  id bigint NOT NULL,
                                  created_at timestamp(6) without time zone,
                                  updated_at timestamp(6) without time zone,
                                  active boolean NOT NULL,
                                  address text,
                                  code character varying(50) NOT NULL,
                                  email character varying(100),
                                  name character varying(150) NOT NULL,
                                  phone character varying(20),
                                  type character varying(20) NOT NULL,
                                  CONSTRAINT customers_type_check CHECK (((type)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'SUPPLIER'::character varying])::text[])))
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 303500)
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 270700)
-- Name: inb_inbound_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inb_inbound_order (
                                          id bigint NOT NULL,
                                          created_at timestamp(6) without time zone,
                                          updated_at timestamp(6) without time zone,
                                          note text,
                                          order_date_time timestamp(6) without time zone,
                                          order_number character varying(255),
                                          status character varying(255),
                                          supplier_name character varying(255),
                                          customer_id bigint NOT NULL,
                                          CONSTRAINT inb_inbound_order_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.inb_inbound_order OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 270699)
-- Name: inb_inbound_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inb_inbound_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inb_inbound_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 270710)
-- Name: inb_inbound_order_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inb_inbound_order_item (
                                               id bigint NOT NULL,
                                               created_at timestamp(6) without time zone,
                                               updated_at timestamp(6) without time zone,
                                               quantity integer NOT NULL,
                                               inbound_order_id bigint,
                                               product_id bigint,
                                               warehouse_id bigint
);


ALTER TABLE public.inb_inbound_order_item OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 270709)
-- Name: inb_inbound_order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inb_inbound_order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inb_inbound_order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 270718)
-- Name: inv_inventory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inv_inventory (
                                      id bigint NOT NULL,
                                      created_at timestamp(6) without time zone,
                                      updated_at timestamp(6) without time zone,
                                      available_quantity integer NOT NULL,
                                      location character varying(255) NOT NULL,
                                      note character varying(255),
                                      quantity integer NOT NULL,
                                      reserved_quantity integer NOT NULL,
                                      status character varying(255) NOT NULL,
                                      version bigint,
                                      product_id bigint NOT NULL,
                                      warehouse_id bigint NOT NULL,
                                      zone_id bigint
);


ALTER TABLE public.inv_inventory OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 270717)
-- Name: inv_inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inv_inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inv_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 303516)
-- Name: inv_inventory_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inv_inventory_log (
                                          id bigint NOT NULL,
                                          created_at timestamp(6) without time zone,
                                          updated_at timestamp(6) without time zone,
                                          movement_type character varying(255) NOT NULL,
                                          order_code character varying(255) NOT NULL,
                                          product_id bigint NOT NULL,
                                          quantity integer NOT NULL
);


ALTER TABLE public.inv_inventory_log OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 303515)
-- Name: inv_inventory_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inv_inventory_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inv_inventory_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 270734)
-- Name: inv_stock_movements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inv_stock_movements (
                                            id bigint NOT NULL,
                                            created_at timestamp(6) without time zone,
                                            updated_at timestamp(6) without time zone,
                                            movement_type character varying(255) NOT NULL,
                                            quantity integer NOT NULL,
                                            reference_code character varying(255),
                                            product_id bigint NOT NULL,
                                            warehouse_id bigint NOT NULL,
                                            product_name character varying(255),
                                            user_id bigint NOT NULL,
                                            user_name character varying(255),
                                            warehouse_name character varying(255),
                                            zone_id bigint NOT NULL,
                                            zone_name character varying(255),
                                            CONSTRAINT inv_stock_movements_movement_type_check CHECK (((movement_type)::text = ANY ((ARRAY['INBOUND'::character varying, 'OUTBOUND'::character varying])::text[])))
);


ALTER TABLE public.inv_stock_movements OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 270733)
-- Name: inv_stock_movements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inv_stock_movements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inv_stock_movements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 303531)
-- Name: inv_stock_transfer_movements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inv_stock_transfer_movements (
                                                     id bigint NOT NULL,
                                                     created_at timestamp(6) without time zone,
                                                     updated_at timestamp(6) without time zone,
                                                     quantity integer NOT NULL,
                                                     reference_code character varying(255),
                                                     from_warehouse_id bigint NOT NULL,
                                                     from_zone_id bigint,
                                                     product_id bigint NOT NULL,
                                                     to_warehouse_id bigint NOT NULL,
                                                     to_zone_id bigint NOT NULL
);


ALTER TABLE public.inv_stock_transfer_movements OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 303530)
-- Name: inv_stock_transfer_movements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inv_stock_transfer_movements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inv_stock_transfer_movements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 303543)
-- Name: inv_transfer_reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inv_transfer_reports (
                                             id bigint NOT NULL,
                                             created_at timestamp(6) without time zone,
                                             updated_at timestamp(6) without time zone,
                                             from_warehouse_id bigint NOT NULL,
                                             from_warehouse_name character varying(255),
                                             from_zone_id bigint NOT NULL,
                                             from_zone_name character varying(255),
                                             movement_type character varying(255) NOT NULL,
                                             product_id bigint NOT NULL,
                                             product_name character varying(255),
                                             quantity integer NOT NULL,
                                             to_warehouse_id bigint NOT NULL,
                                             to_warehouse_name character varying(255),
                                             to_zone_id bigint NOT NULL,
                                             to_zone_name character varying(255),
                                             user_id bigint NOT NULL,
                                             CONSTRAINT inv_transfer_reports_movement_type_check CHECK (((movement_type)::text = ANY ((ARRAY['INBOUND'::character varying, 'OUTBOUND'::character varying, 'TRANSFER_IN'::character varying, 'TRANSFER_OUT'::character varying, 'TRANSFER'::character varying])::text[])))
);


ALTER TABLE public.inv_transfer_reports OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 303542)
-- Name: inv_transfer_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inv_transfer_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inv_transfer_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 270748)
-- Name: out_outbound_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.out_outbound_order (
                                           id bigint NOT NULL,
                                           created_at timestamp(6) without time zone,
                                           updated_at timestamp(6) without time zone,
                                           customer_name character varying(255) NOT NULL,
                                           note text,
                                           order_code character varying(255),
                                           order_date_time timestamp(6) without time zone,
                                           status character varying(255) NOT NULL,
                                           request_id character varying(255),
                                           customer_id bigint,
                                           CONSTRAINT out_outbound_order_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.out_outbound_order OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 270747)
-- Name: out_outbound_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.out_outbound_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.out_outbound_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 270760)
-- Name: out_outbound_order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.out_outbound_order_items (
                                                 id bigint NOT NULL,
                                                 created_at timestamp(6) without time zone,
                                                 updated_at timestamp(6) without time zone,
                                                 quantity integer NOT NULL,
                                                 outbound_order_id bigint NOT NULL,
                                                 product_id bigint NOT NULL,
                                                 warehouse_id bigint NOT NULL,
                                                 zone_id bigint NOT NULL
);


ALTER TABLE public.out_outbound_order_items OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 270759)
-- Name: out_outbound_order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.out_outbound_order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.out_outbound_order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 303562)
-- Name: outbox_inventory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.outbox_inventory (
                                         id bigint NOT NULL,
                                         created_at timestamp(6) without time zone,
                                         updated_at timestamp(6) without time zone,
                                         event_type character varying(100) NOT NULL,
                                         last_error text,
                                         order_code character varying(255) NOT NULL,
                                         pay_load text NOT NULL,
                                         retry_count integer NOT NULL,
                                         status character varying(20) NOT NULL,
                                         topic character varying(100) NOT NULL,
                                         CONSTRAINT outbox_inventory_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SENT'::character varying, 'FAILED'::character varying, 'DEAD'::character varying])::text[])))
);


ALTER TABLE public.outbox_inventory OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 303561)
-- Name: outbox_inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.outbox_inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbox_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 270771)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
                                 id bigint NOT NULL,
                                 created_at timestamp(6) without time zone,
                                 updated_at timestamp(6) without time zone,
                                 description text,
                                 name character varying(255) NOT NULL,
                                 price numeric(19,2) NOT NULL,
                                 sku character varying(255) NOT NULL,
                                 stock integer NOT NULL,
                                 unit character varying(255),
                                 active boolean NOT NULL,
                                 category_id bigint
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 303578)
-- Name: products_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_category (
                                          id bigint NOT NULL,
                                          created_at timestamp(6) without time zone,
                                          updated_at timestamp(6) without time zone,
                                          active boolean NOT NULL,
                                          description text,
                                          name character varying(100) NOT NULL
);


ALTER TABLE public.products_category OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 303577)
-- Name: products_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 270770)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 270784)
-- Name: wh_warehouse; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wh_warehouse (
                                     id bigint NOT NULL,
                                     created_at timestamp(6) without time zone,
                                     updated_at timestamp(6) without time zone,
                                     active boolean NOT NULL,
                                     capacity integer NOT NULL,
                                     code character varying(50) NOT NULL,
                                     location text,
                                     name character varying(100) NOT NULL
);


ALTER TABLE public.wh_warehouse OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 270783)
-- Name: wh_warehouse_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wh_warehouse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wh_warehouse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 303589)
-- Name: wh_zone; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wh_zone (
                                id bigint NOT NULL,
                                created_at timestamp(6) without time zone,
                                updated_at timestamp(6) without time zone,
                                active boolean NOT NULL,
                                capacity integer NOT NULL,
                                code character varying(50) NOT NULL,
                                name character varying(100) NOT NULL,
                                warehouse_id bigint NOT NULL,
                                CONSTRAINT wh_zone_capacity_check CHECK ((capacity >= 0))
);


ALTER TABLE public.wh_zone OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 303588)
-- Name: wh_zone_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wh_zone ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wh_zone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5237 (class 0 OID 303480)
-- Dependencies: 241
-- Data for Name: aut_permission_perwarehouse; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.aut_permission_perwarehouse (id, created_at, updated_at, granted_at, grant_by, permission_id, user_id, warehouse_id) FROM stdin;
\.


--
-- TOC entry 5239 (class 0 OID 303491)
-- Dependencies: 243
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, created_at, updated_at, code, description) FROM stdin;
\.


--
-- TOC entry 5255 (class 0 OID 303695)
-- Dependencies: 259
-- Data for Name: auth_refresh_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_refresh_token (id, created_at, updated_at, created_by_ip, expires_at, replaced_by_token_hash, revoked, token_hash, user_agent, user_id) FROM stdin;
\.


--
-- TOC entry 5216 (class 0 OID 246118)
-- Dependencies: 220
-- Data for Name: auth_role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_role (id, created_at, updated_at, name) FROM stdin;
1	2026-04-02 19:33:52.741094	2026-04-02 19:33:52.741094	ROLE_ADMIN
2	2026-04-02 19:33:52.888341	2026-04-02 19:33:52.888341	ROLE_USER
3	2026-04-02 19:33:52.897933	2026-04-02 19:33:52.897933	ROLE_MANAGER
\.


--
-- TOC entry 5218 (class 0 OID 246125)
-- Dependencies: 222
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, created_at, updated_at, email, password, username) FROM stdin;
2	2026-04-02 20:30:33.080768	2026-04-02 20:30:33.080768	dungvt1602@gmail.com	$2a$10$skGE1qs9wCNrPV5wNsnjneyGYSAOeZ2NdOj9n3qu6HDzXNTCI0GSm	dungvt1602
\.


--
-- TOC entry 5219 (class 0 OID 246133)
-- Dependencies: 223
-- Data for Name: auth_user_role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_role (user_id, role_id) FROM stdin;
2	2
\.


--
-- TOC entry 5241 (class 0 OID 303501)
-- Dependencies: 245
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers (id, created_at, updated_at, active, address, code, email, name, phone, type) FROM stdin;
\.


--
-- TOC entry 5221 (class 0 OID 270700)
-- Dependencies: 225
-- Data for Name: inb_inbound_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inb_inbound_order (id, created_at, updated_at, note, order_date_time, order_number, status, supplier_name, customer_id) FROM stdin;
\.


--
-- TOC entry 5223 (class 0 OID 270710)
-- Dependencies: 227
-- Data for Name: inb_inbound_order_item; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inb_inbound_order_item (id, created_at, updated_at, quantity, inbound_order_id, product_id, warehouse_id) FROM stdin;
\.


--
-- TOC entry 5225 (class 0 OID 270718)
-- Dependencies: 229
-- Data for Name: inv_inventory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inv_inventory (id, created_at, updated_at, available_quantity, location, note, quantity, reserved_quantity, status, version, product_id, warehouse_id, zone_id) FROM stdin;
\.


--
-- TOC entry 5243 (class 0 OID 303516)
-- Dependencies: 247
-- Data for Name: inv_inventory_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inv_inventory_log (id, created_at, updated_at, movement_type, order_code, product_id, quantity) FROM stdin;
\.


--
-- TOC entry 5227 (class 0 OID 270734)
-- Dependencies: 231
-- Data for Name: inv_stock_movements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inv_stock_movements (id, created_at, updated_at, movement_type, quantity, reference_code, product_id, warehouse_id, product_name, user_id, user_name, warehouse_name, zone_id, zone_name) FROM stdin;
\.


--
-- TOC entry 5245 (class 0 OID 303531)
-- Dependencies: 249
-- Data for Name: inv_stock_transfer_movements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inv_stock_transfer_movements (id, created_at, updated_at, quantity, reference_code, from_warehouse_id, from_zone_id, product_id, to_warehouse_id, to_zone_id) FROM stdin;
\.


--
-- TOC entry 5247 (class 0 OID 303543)
-- Dependencies: 251
-- Data for Name: inv_transfer_reports; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inv_transfer_reports (id, created_at, updated_at, from_warehouse_id, from_warehouse_name, from_zone_id, from_zone_name, movement_type, product_id, product_name, quantity, to_warehouse_id, to_warehouse_name, to_zone_id, to_zone_name, user_id) FROM stdin;
\.


--
-- TOC entry 5229 (class 0 OID 270748)
-- Dependencies: 233
-- Data for Name: out_outbound_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.out_outbound_order (id, created_at, updated_at, customer_name, note, order_code, order_date_time, status, request_id, customer_id) FROM stdin;
\.


--
-- TOC entry 5231 (class 0 OID 270760)
-- Dependencies: 235
-- Data for Name: out_outbound_order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.out_outbound_order_items (id, created_at, updated_at, quantity, outbound_order_id, product_id, warehouse_id, zone_id) FROM stdin;
\.


--
-- TOC entry 5249 (class 0 OID 303562)
-- Dependencies: 253
-- Data for Name: outbox_inventory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.outbox_inventory (id, created_at, updated_at, event_type, last_error, order_code, pay_load, retry_count, status, topic) FROM stdin;
\.


--
-- TOC entry 5233 (class 0 OID 270771)
-- Dependencies: 237
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, created_at, updated_at, description, name, price, sku, stock, unit, active, category_id) FROM stdin;
\.


--
-- TOC entry 5251 (class 0 OID 303578)
-- Dependencies: 255
-- Data for Name: products_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products_category (id, created_at, updated_at, active, description, name) FROM stdin;
\.


--
-- TOC entry 5235 (class 0 OID 270784)
-- Dependencies: 239
-- Data for Name: wh_warehouse; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wh_warehouse (id, created_at, updated_at, active, capacity, code, location, name) FROM stdin;
\.


--
-- TOC entry 5253 (class 0 OID 303589)
-- Dependencies: 257
-- Data for Name: wh_zone; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wh_zone (id, created_at, updated_at, active, capacity, code, name, warehouse_id) FROM stdin;
\.


--
-- TOC entry 5261 (class 0 OID 0)
-- Dependencies: 240
-- Name: aut_permission_perwarehouse_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.aut_permission_perwarehouse_id_seq', 1, false);


--
-- TOC entry 5262 (class 0 OID 0)
-- Dependencies: 242
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 1, false);


--
-- TOC entry 5263 (class 0 OID 0)
-- Dependencies: 258
-- Name: auth_refresh_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_refresh_token_id_seq', 1, false);


--
-- TOC entry 5264 (class 0 OID 0)
-- Dependencies: 219
-- Name: auth_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_role_id_seq', 3, true);


--
-- TOC entry 5265 (class 0 OID 0)
-- Dependencies: 221
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- TOC entry 5266 (class 0 OID 0)
-- Dependencies: 244
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_id_seq', 1, false);


--
-- TOC entry 5267 (class 0 OID 0)
-- Dependencies: 224
-- Name: inb_inbound_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inb_inbound_order_id_seq', 1, false);


--
-- TOC entry 5268 (class 0 OID 0)
-- Dependencies: 226
-- Name: inb_inbound_order_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inb_inbound_order_item_id_seq', 1, false);


--
-- TOC entry 5269 (class 0 OID 0)
-- Dependencies: 228
-- Name: inv_inventory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inv_inventory_id_seq', 1, false);


--
-- TOC entry 5270 (class 0 OID 0)
-- Dependencies: 246
-- Name: inv_inventory_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inv_inventory_log_id_seq', 1, false);


--
-- TOC entry 5271 (class 0 OID 0)
-- Dependencies: 230
-- Name: inv_stock_movements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inv_stock_movements_id_seq', 1, false);


--
-- TOC entry 5272 (class 0 OID 0)
-- Dependencies: 248
-- Name: inv_stock_transfer_movements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inv_stock_transfer_movements_id_seq', 1, false);


--
-- TOC entry 5273 (class 0 OID 0)
-- Dependencies: 250
-- Name: inv_transfer_reports_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inv_transfer_reports_id_seq', 1, false);


--
-- TOC entry 5274 (class 0 OID 0)
-- Dependencies: 232
-- Name: out_outbound_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.out_outbound_order_id_seq', 1, false);


--
-- TOC entry 5275 (class 0 OID 0)
-- Dependencies: 234
-- Name: out_outbound_order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.out_outbound_order_items_id_seq', 1, false);


--
-- TOC entry 5276 (class 0 OID 0)
-- Dependencies: 252
-- Name: outbox_inventory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.outbox_inventory_id_seq', 1, false);


--
-- TOC entry 5277 (class 0 OID 0)
-- Dependencies: 254
-- Name: products_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_category_id_seq', 1, false);


--
-- TOC entry 5278 (class 0 OID 0)
-- Dependencies: 236
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 1, false);


--
-- TOC entry 5279 (class 0 OID 0)
-- Dependencies: 238
-- Name: wh_warehouse_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.wh_warehouse_id_seq', 1, false);


--
-- TOC entry 5280 (class 0 OID 0)
-- Dependencies: 256
-- Name: wh_zone_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.wh_zone_id_seq', 1, false);


--
-- TOC entry 5001 (class 2606 OID 303489)
-- Name: aut_permission_perwarehouse aut_permission_perwarehouse_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aut_permission_perwarehouse
    ADD CONSTRAINT aut_permission_perwarehouse_pkey PRIMARY KEY (id);


--
-- TOC entry 5007 (class 2606 OID 303499)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 5038 (class 2606 OID 303706)
-- Name: auth_refresh_token auth_refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_refresh_token
    ADD CONSTRAINT auth_refresh_token_pkey PRIMARY KEY (id);


--
-- TOC entry 4963 (class 2606 OID 246123)
-- Name: auth_role auth_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_role
    ADD CONSTRAINT auth_role_pkey PRIMARY KEY (id);


--
-- TOC entry 4965 (class 2606 OID 246132)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4967 (class 2606 OID 246139)
-- Name: auth_user_role auth_user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_role
    ADD CONSTRAINT auth_user_role_pkey PRIMARY KEY (user_id, role_id);


--
-- TOC entry 5011 (class 2606 OID 303513)
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- TOC entry 4973 (class 2606 OID 270716)
-- Name: inb_inbound_order_item inb_inbound_order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inb_inbound_order_item
    ADD CONSTRAINT inb_inbound_order_item_pkey PRIMARY KEY (id);


--
-- TOC entry 4969 (class 2606 OID 270708)
-- Name: inb_inbound_order inb_inbound_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inb_inbound_order
    ADD CONSTRAINT inb_inbound_order_pkey PRIMARY KEY (id);


--
-- TOC entry 5017 (class 2606 OID 303527)
-- Name: inv_inventory_log inv_inventory_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_inventory_log
    ADD CONSTRAINT inv_inventory_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4975 (class 2606 OID 270732)
-- Name: inv_inventory inv_inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_inventory
    ADD CONSTRAINT inv_inventory_pkey PRIMARY KEY (id);


--
-- TOC entry 4981 (class 2606 OID 270746)
-- Name: inv_stock_movements inv_stock_movements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_stock_movements
    ADD CONSTRAINT inv_stock_movements_pkey PRIMARY KEY (id);


--
-- TOC entry 5021 (class 2606 OID 303541)
-- Name: inv_stock_transfer_movements inv_stock_transfer_movements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_stock_transfer_movements
    ADD CONSTRAINT inv_stock_transfer_movements_pkey PRIMARY KEY (id);


--
-- TOC entry 5023 (class 2606 OID 303559)
-- Name: inv_transfer_reports inv_transfer_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_transfer_reports
    ADD CONSTRAINT inv_transfer_reports_pkey PRIMARY KEY (id);


--
-- TOC entry 4989 (class 2606 OID 270769)
-- Name: out_outbound_order_items out_outbound_order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.out_outbound_order_items
    ADD CONSTRAINT out_outbound_order_items_pkey PRIMARY KEY (id);


--
-- TOC entry 4983 (class 2606 OID 270758)
-- Name: out_outbound_order out_outbound_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.out_outbound_order
    ADD CONSTRAINT out_outbound_order_pkey PRIMARY KEY (id);


--
-- TOC entry 5026 (class 2606 OID 303576)
-- Name: outbox_inventory outbox_inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.outbox_inventory
    ADD CONSTRAINT outbox_inventory_pkey PRIMARY KEY (id);


--
-- TOC entry 5030 (class 2606 OID 303587)
-- Name: products_category products_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_pkey PRIMARY KEY (id);


--
-- TOC entry 4991 (class 2606 OID 270782)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 4971 (class 2606 OID 270797)
-- Name: inb_inbound_order uk321vrlbck6enoyk41ucit6gvo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inb_inbound_order
    ADD CONSTRAINT uk321vrlbck6enoyk41ucit6gvo UNIQUE (order_number);


--
-- TOC entry 4977 (class 2606 OID 303612)
-- Name: inv_inventory uk4n5nbbq7uq2duqfp5og3y3xpa; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_inventory
    ADD CONSTRAINT uk4n5nbbq7uq2duqfp5og3y3xpa UNIQUE (warehouse_id, product_id, zone_id);


--
-- TOC entry 5034 (class 2606 OID 303623)
-- Name: wh_zone uk8m38m5wumg6k6lgvo0bugqp4q; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wh_zone
    ADD CONSTRAINT uk8m38m5wumg6k6lgvo0bugqp4q UNIQUE (code);


--
-- TOC entry 4979 (class 2606 OID 270799)
-- Name: inv_inventory uka8a6xtse420hxsd63agg6xvw3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_inventory
    ADD CONSTRAINT uka8a6xtse420hxsd63agg6xvw3 UNIQUE (warehouse_id, product_id);


--
-- TOC entry 4993 (class 2606 OID 270805)
-- Name: products ukfhmd06dsmj6k0n90swsh8ie9g; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT ukfhmd06dsmj6k0n90swsh8ie9g UNIQUE (sku);


--
-- TOC entry 5040 (class 2606 OID 303708)
-- Name: auth_refresh_token ukguf0204l9e7p3x4cjwyprkhuc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_refresh_token
    ADD CONSTRAINT ukguf0204l9e7p3x4cjwyprkhuc UNIQUE (token_hash);


--
-- TOC entry 4985 (class 2606 OID 303616)
-- Name: out_outbound_order uki7r2fcu377uiauqoux7652p4r; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.out_outbound_order
    ADD CONSTRAINT uki7r2fcu377uiauqoux7652p4r UNIQUE (request_id);


--
-- TOC entry 5032 (class 2606 OID 303621)
-- Name: products_category ukly9xwm58fa3ch75kibwemi5er; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT ukly9xwm58fa3ch75kibwemi5er UNIQUE (name);


--
-- TOC entry 4987 (class 2606 OID 270801)
-- Name: out_outbound_order ukm3xxkfraoobxnqfdl0yp6g7gb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.out_outbound_order
    ADD CONSTRAINT ukm3xxkfraoobxnqfdl0yp6g7gb UNIQUE (order_code);


--
-- TOC entry 5013 (class 2606 OID 303608)
-- Name: customers ukmkwx1x9mthieapj92cpxq5msc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT ukmkwx1x9mthieapj92cpxq5msc UNIQUE (code);


--
-- TOC entry 4997 (class 2606 OID 270807)
-- Name: wh_warehouse ukmuwi9ticeixbl8qe0o2b66sll; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wh_warehouse
    ADD CONSTRAINT ukmuwi9ticeixbl8qe0o2b66sll UNIQUE (code);


--
-- TOC entry 4995 (class 2606 OID 270803)
-- Name: products uko61fmio5yukmmiqgnxf8pnavn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT uko61fmio5yukmmiqgnxf8pnavn UNIQUE (name);


--
-- TOC entry 5028 (class 2606 OID 303619)
-- Name: outbox_inventory ukqsufe40dy4i4x2g4pn5eb8yf7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.outbox_inventory
    ADD CONSTRAINT ukqsufe40dy4i4x2g4pn5eb8yf7 UNIQUE (order_code);


--
-- TOC entry 5009 (class 2606 OID 303606)
-- Name: auth_permission uksomba37al7jncqwbq818vx13e; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT uksomba37al7jncqwbq818vx13e UNIQUE (code);


--
-- TOC entry 5015 (class 2606 OID 303610)
-- Name: customers ukto73biqfrti0j9f7k12l255w5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT ukto73biqfrti0j9f7k12l255w5 UNIQUE (name);


--
-- TOC entry 5019 (class 2606 OID 303614)
-- Name: inv_inventory_log uq_order_product; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_inventory_log
    ADD CONSTRAINT uq_order_product UNIQUE (order_code, product_id);


--
-- TOC entry 5005 (class 2606 OID 303604)
-- Name: aut_permission_perwarehouse uq_warehouse_userid; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aut_permission_perwarehouse
    ADD CONSTRAINT uq_warehouse_userid UNIQUE (user_id, warehouse_id, permission_id);


--
-- TOC entry 4999 (class 2606 OID 270795)
-- Name: wh_warehouse wh_warehouse_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wh_warehouse
    ADD CONSTRAINT wh_warehouse_pkey PRIMARY KEY (id);


--
-- TOC entry 5036 (class 2606 OID 303600)
-- Name: wh_zone wh_zone_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wh_zone
    ADD CONSTRAINT wh_zone_pkey PRIMARY KEY (id);


--
-- TOC entry 5024 (class 1259 OID 303617)
-- Name: idx_outbox_status_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_outbox_status_created ON public.outbox_inventory USING btree (status, created_at);


--
-- TOC entry 5002 (class 1259 OID 303602)
-- Name: idx_uwp_warehouse; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_uwp_warehouse ON public.aut_permission_perwarehouse USING btree (warehouse_id);


--
-- TOC entry 5003 (class 1259 OID 303601)
-- Name: idx_warehouse_userid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_warehouse_userid ON public.aut_permission_perwarehouse USING btree (warehouse_id, user_id);


--
-- TOC entry 5044 (class 2606 OID 270818)
-- Name: inb_inbound_order_item fk29mraxov3mfti635xi93eiwua; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inb_inbound_order_item
    ADD CONSTRAINT fk29mraxov3mfti635xi93eiwua FOREIGN KEY (warehouse_id) REFERENCES public.wh_warehouse(id);


--
-- TOC entry 5052 (class 2606 OID 303674)
-- Name: out_outbound_order fk2ut2n26y1gden5vnh92c4n68g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.out_outbound_order
    ADD CONSTRAINT fk2ut2n26y1gden5vnh92c4n68g FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- TOC entry 5061 (class 2606 OID 303649)
-- Name: inv_stock_transfer_movements fk3ci1mlfgmkfblxvmmvpby09o7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_stock_transfer_movements
    ADD CONSTRAINT fk3ci1mlfgmkfblxvmmvpby09o7 FOREIGN KEY (from_warehouse_id) REFERENCES public.wh_warehouse(id);


--
-- TOC entry 5041 (class 2606 OID 246140)
-- Name: auth_user_role fk3eldmba9luu9l0apl0791x8vd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_role
    ADD CONSTRAINT fk3eldmba9luu9l0apl0791x8vd FOREIGN KEY (role_id) REFERENCES public.auth_role(id);


--
-- TOC entry 5062 (class 2606 OID 303669)
-- Name: inv_stock_transfer_movements fk3y838qf13bk9w1uv1sh31owdd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_stock_transfer_movements
    ADD CONSTRAINT fk3y838qf13bk9w1uv1sh31owdd FOREIGN KEY (to_zone_id) REFERENCES public.wh_zone(id);


--
-- TOC entry 5045 (class 2606 OID 270808)
-- Name: inb_inbound_order_item fk4l00pnumwjvsr0c2pr8pb17mj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inb_inbound_order_item
    ADD CONSTRAINT fk4l00pnumwjvsr0c2pr8pb17mj FOREIGN KEY (inbound_order_id) REFERENCES public.inb_inbound_order(id);


--
-- TOC entry 5053 (class 2606 OID 270848)
-- Name: out_outbound_order_items fk4rwod76xqk2xok9jvja2qxusg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.out_outbound_order_items
    ADD CONSTRAINT fk4rwod76xqk2xok9jvja2qxusg FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 5058 (class 2606 OID 303634)
-- Name: aut_permission_perwarehouse fk7os59llby6c3ls50bkkgg1ub3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aut_permission_perwarehouse
    ADD CONSTRAINT fk7os59llby6c3ls50bkkgg1ub3 FOREIGN KEY (warehouse_id) REFERENCES public.wh_warehouse(id);


--
-- TOC entry 5047 (class 2606 OID 303644)
-- Name: inv_inventory fk7ue94la5eumvsc7m86l371u61; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_inventory
    ADD CONSTRAINT fk7ue94la5eumvsc7m86l371u61 FOREIGN KEY (zone_id) REFERENCES public.wh_zone(id);


--
-- TOC entry 5057 (class 2606 OID 303684)
-- Name: products fk9p9v92c6k9qj6pgfjmweqs5mr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk9p9v92c6k9qj6pgfjmweqs5mr FOREIGN KEY (category_id) REFERENCES public.products_category(id);


--
-- TOC entry 5059 (class 2606 OID 303624)
-- Name: aut_permission_perwarehouse fkboob0y5nk8saf5d2ldqjqruqd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aut_permission_perwarehouse
    ADD CONSTRAINT fkboob0y5nk8saf5d2ldqjqruqd FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id);


--
-- TOC entry 5063 (class 2606 OID 303664)
-- Name: inv_stock_transfer_movements fkc97g5no4o3lidqbtcfi4leye; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_stock_transfer_movements
    ADD CONSTRAINT fkc97g5no4o3lidqbtcfi4leye FOREIGN KEY (to_warehouse_id) REFERENCES public.wh_warehouse(id);


--
-- TOC entry 5054 (class 2606 OID 270853)
-- Name: out_outbound_order_items fkdp6fevut3ervspg6t2p0j86k5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.out_outbound_order_items
    ADD CONSTRAINT fkdp6fevut3ervspg6t2p0j86k5 FOREIGN KEY (warehouse_id) REFERENCES public.wh_warehouse(id);


--
-- TOC entry 5042 (class 2606 OID 246145)
-- Name: auth_user_role fkebutsbqm58ehnlffb299ng0ap; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_role
    ADD CONSTRAINT fkebutsbqm58ehnlffb299ng0ap FOREIGN KEY (user_id) REFERENCES public.auth_user(id);


--
-- TOC entry 5060 (class 2606 OID 303629)
-- Name: aut_permission_perwarehouse fkftt1iariabiagvb1n81idpj9d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aut_permission_perwarehouse
    ADD CONSTRAINT fkftt1iariabiagvb1n81idpj9d FOREIGN KEY (user_id) REFERENCES public.auth_user(id);


--
-- TOC entry 5048 (class 2606 OID 270823)
-- Name: inv_inventory fkhjhenmg01r2eax3takpls7j8x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_inventory
    ADD CONSTRAINT fkhjhenmg01r2eax3takpls7j8x FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 5067 (class 2606 OID 303709)
-- Name: auth_refresh_token fkhqbplqpdaqhxrwf6dynphwsy8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_refresh_token
    ADD CONSTRAINT fkhqbplqpdaqhxrwf6dynphwsy8 FOREIGN KEY (user_id) REFERENCES public.auth_user(id);


--
-- TOC entry 5050 (class 2606 OID 270833)
-- Name: inv_stock_movements fkiod4aigjahekxtg1g4ll5v3gy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_stock_movements
    ADD CONSTRAINT fkiod4aigjahekxtg1g4ll5v3gy FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 5055 (class 2606 OID 303679)
-- Name: out_outbound_order_items fkiqgsvelodmn8tltosufdcw6j2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.out_outbound_order_items
    ADD CONSTRAINT fkiqgsvelodmn8tltosufdcw6j2 FOREIGN KEY (zone_id) REFERENCES public.wh_zone(id);


--
-- TOC entry 5051 (class 2606 OID 270838)
-- Name: inv_stock_movements fkjgy4epgh7kblm15mh1hu5ij8e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_stock_movements
    ADD CONSTRAINT fkjgy4epgh7kblm15mh1hu5ij8e FOREIGN KEY (warehouse_id) REFERENCES public.wh_warehouse(id);


--
-- TOC entry 5064 (class 2606 OID 303654)
-- Name: inv_stock_transfer_movements fkm1r7vg1nm1h1vig8b0aj4ovvj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_stock_transfer_movements
    ADD CONSTRAINT fkm1r7vg1nm1h1vig8b0aj4ovvj FOREIGN KEY (from_zone_id) REFERENCES public.wh_zone(id);


--
-- TOC entry 5056 (class 2606 OID 270843)
-- Name: out_outbound_order_items fkm3plw3py60hkwip22hu2jqwu5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.out_outbound_order_items
    ADD CONSTRAINT fkm3plw3py60hkwip22hu2jqwu5 FOREIGN KEY (outbound_order_id) REFERENCES public.out_outbound_order(id);


--
-- TOC entry 5049 (class 2606 OID 270828)
-- Name: inv_inventory fkm7wmoxlmg3inavxj6prcf6poc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_inventory
    ADD CONSTRAINT fkm7wmoxlmg3inavxj6prcf6poc FOREIGN KEY (warehouse_id) REFERENCES public.wh_warehouse(id);


--
-- TOC entry 5046 (class 2606 OID 270813)
-- Name: inb_inbound_order_item fkmadhsmdvjct79gshcvye1sf6n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inb_inbound_order_item
    ADD CONSTRAINT fkmadhsmdvjct79gshcvye1sf6n FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 5066 (class 2606 OID 303689)
-- Name: wh_zone fkou18ck8sard9rbs5d7bmooums; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wh_zone
    ADD CONSTRAINT fkou18ck8sard9rbs5d7bmooums FOREIGN KEY (warehouse_id) REFERENCES public.wh_warehouse(id);


--
-- TOC entry 5043 (class 2606 OID 303639)
-- Name: inb_inbound_order fkpxh05i9ckcx7thxx5o680j5yb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inb_inbound_order
    ADD CONSTRAINT fkpxh05i9ckcx7thxx5o680j5yb FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- TOC entry 5065 (class 2606 OID 303659)
-- Name: inv_stock_transfer_movements fkt1ifutwx5d5xwk3tnkx0s3937; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inv_stock_transfer_movements
    ADD CONSTRAINT fkt1ifutwx5d5xwk3tnkx0s3937 FOREIGN KEY (product_id) REFERENCES public.products(id);


-- Completed on 2026-05-01 20:55:01

--
-- PostgreSQL database dump complete
--

\unrestrict XFQ6PN2qt7h0h3dVcqeuLuk4mcwvYidjQfIPgR10eSZU9aH4OGcbmHww6istebx

